apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: airan-system

resources:
  - ../../config/crd/bases/airan.io_qosawareworkloads.yaml
  - ../../config/crd/bases/migpartitionconfig_crd.yaml
  - ../../config/rbac/role.yaml
  - ../../config/manager/deployment.yaml

commonLabels:
  app.kubernetes.io/name: ai-ran-orchestrator
  app.kubernetes.io/part-of: airan

images:
  - name: ai-ran-orchestrator
    newTag: latest
